DEFAULT_IMAGE_SIZE = 100
DEFAULT_EMBEDDING_DIM = 128
DEFAULT_DROPOUT = 0.2
DEFAULT_ACTIVATION = "relu"

DEFAULT_DATA_ROOT = (
    "/home/haloandrei/.cache/kagglehub/datasets/moltean/fruits/versions/75/"
    "fruits-360_100x100/fruits-360/Training"
)
DEFAULT_VAL_RATIO = 0.2

DEFAULT_BATCH_SIZE = 64
DEFAULT_NUM_WORKERS = 2
DEFAULT_EPOCHS = 10
DEFAULT_LR = 1e-3
DEFAULT_WEIGHT_DECAY = 1e-4
DEFAULT_MAX_SAMPLES = 0
DEFAULT_SEED = 42

DEFAULT_K = 10
DEFAULT_KMEANS_ITERS = 50

DEFAULT_RL_EPISODES = 10
DEFAULT_RL_STEPS = 8
DEFAULT_TUNE_EPOCHS = 2
